// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auth struct {
	ID   string `json:"id"`
	User *User  `json:"user"`
}

type User struct {
	Name string `json:"name"`
	ID   string `json:"id"`
	Age  *int   `json:"age"`
}
